/* iso532 C ABI — v0, pre-1.0: may change until R5 freezes v1 (risk R-17).
 * Generated by cbindgen from iso532-ffi; do not edit by hand.
 * Regenerate: cbindgen --config cbindgen.toml --crate iso532-ffi --output include/iso532.h */

#ifndef ISO532_H
#define ISO532_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define ISO532_OK 0

#define ISO532_ERR_LEVEL_EXCEEDS_120DB 1

#define ISO532_ERR_SIGNAL_TOO_SHORT 2

#define ISO532_ERR_UNSUPPORTED_SAMPLE_RATE 3

#define ISO532_ERR_NULL_POINTER -1

#define ISO532_ERR_PANIC -2

#define ISO532_ERR_INVALID_FIELD_TYPE -3

/**
 * 程式庫內部不變量被打破；輸出緩衝未被寫入。
 */
#define ISO532_ERR_INTERNAL -4

/**
 * field_type 合法值：自由場。
 */
#define ISO532_FIELD_FREE 0

/**
 * field_type 合法值：擴散場。
 */
#define ISO532_FIELD_DIFFUSE 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Number of output frames `iso532_loudness_zwtv` will write for a signal of
 * `signal_len` samples, on the ISO 2 ms output grid. Pure; does not validate
 * (validation happens in the main call). Forwards `iso532::zwtv_out_frames`.
 */
size_t iso532_zwtv_out_frames(size_t signal_len);

/**
 * Time-varying (zwtv) loudness. Caller allocates every buffer:
 * out_n[frames], out_n_specific[240*frames] (bark-major, row-major),
 * out_bark[240], out_time[frames]; frames = iso532_zwtv_out_frames(signal_len).
 * Returns 0 on success (see error-code defines). Uses a process-wide thread
 * pool (rayon).
 *
 * # Safety
 * `signal` must be non-null, 8-byte aligned (a valid `double*`), and valid
 * for `signal_len` reads; each out pointer must be valid (and 8-byte
 * aligned) for the writes documented above. `field_type` must be
 * ISO532_FIELD_FREE (0) or ISO532_FIELD_DIFFUSE (1); other values return
 * ISO532_ERR_INVALID_FIELD_TYPE.
 */
int32_t iso532_loudness_zwtv(const double *signal,
                             size_t signal_len,
                             double fs,
                             int32_t field_type,
                             double *out_n,
                             double *out_n_specific,
                             double *out_bark,
                             double *out_time);

/**
 * Stationary (zwst) loudness. Caller allocates: out_n[1],
 * out_n_specific[240], out_bark[240]. Returns 0 on success.
 *
 * # Safety
 * `signal` must be non-null, 8-byte aligned (a valid `double*`), and valid
 * for `signal_len` reads; each out pointer must be valid (and 8-byte
 * aligned) for the writes documented above. `field_type` must be
 * ISO532_FIELD_FREE (0) or ISO532_FIELD_DIFFUSE (1); other values return
 * ISO532_ERR_INVALID_FIELD_TYPE.
 */
int32_t iso532_loudness_zwst(const double *signal,
                             size_t signal_len,
                             double fs,
                             int32_t field_type,
                             double *out_n,
                             double *out_n_specific,
                             double *out_bark);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ISO532_H */
