/* iso532 C ABI v1 — batch and streaming interfaces are frozen.
 * Generated by cbindgen from iso532-ffi; do not edit by hand.
 * Regenerate: cbindgen --config cbindgen.toml --crate iso532-ffi --output include/iso532.h */

#ifndef ISO532_H
#define ISO532_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define ISO532_OK 0

#define ISO532_ERR_LEVEL_EXCEEDS_120DB 1

#define ISO532_ERR_SIGNAL_TOO_SHORT 2

#define ISO532_ERR_UNSUPPORTED_SAMPLE_RATE 3

#define ISO532_ERR_NULL_POINTER -1

#define ISO532_ERR_PANIC -2

#define ISO532_ERR_INVALID_FIELD_TYPE -3

/**
 * An internal invariant was broken. Stream push/flush also use this code to
 * reject an insufficient out_cap without writing a partial result.
 */
#define ISO532_ERR_INTERNAL -4

/**
 * field_type 合法值：自由場。
 */
#define ISO532_FIELD_FREE 0

/**
 * field_type 合法值：擴散場。
 */
#define ISO532_FIELD_DIFFUSE 1

#define ISO532_STREAM_FLAG_CLAMPED_120DB 1

#define ISO532_STREAM_FLAG_NONFINITE_INPUT 2

#define ISO532_STREAM_FLAG_WARMUP 4

/**
 * Opaque stream handle allocated by iso532_stream_new and released by
 * iso532_stream_free. A handle has no internal lock and must not be called
 * concurrently from multiple threads.
 */
typedef struct Iso532Stream Iso532Stream;

/**
 * One 2 ms stream output frame.
 *
 * `flags` uses bit 1 for CLAMPED_120DB, bit 2 for NONFINITE_INPUT, and bit 4
 * for WARMUP. WARMUP is set while `t_frame_index < 580`.
 */
typedef struct Iso532StreamFrame {
  uint64_t t_frame_index;
  double n;
  double n_phon;
  uint32_t flags;
  uint32_t _reserved;
} Iso532StreamFrame;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Allocate a baked-in 48 kHz stream with 24 samples (one internal frame) of
 * latency. An invalid field_type returns NULL.
 */
struct Iso532Stream *iso532_stream_new(int32_t field_type);

size_t iso532_stream_max_frames(size_t chunk_len);

/**
 * Push a 48 kHz signal chunk into a stream handle.
 *
 * `out` must hold at least `iso532_stream_max_frames(chunk_len)` frames. An
 * insufficient out_cap returns -4, sets `*out_written` to zero, and writes no
 * partial result. A panic returns -2 and poisons the handle; only
 * iso532_stream_free may be called afterward. A push after flush also returns
 * -2 through the internal assertion and has the same poisoned-handle rule.
 *
 * # Safety
 * The handle must be live, chunk must contain chunk_len readable doubles,
 * out must contain out_cap writable frames, and out_written must be writable.
 */
int32_t iso532_stream_push(struct Iso532Stream *handle,
                           const double *chunk,
                           size_t chunk_len,
                           struct Iso532StreamFrame *out,
                           size_t out_cap,
                           size_t *out_written);

/**
 * Flush the final lookahead frame. out_cap must be at least one. After flush,
 * only iso532_stream_free may be called through the C API.
 *
 * # Safety
 * The handle must be live, out must contain at least one writable frame,
 * and out_written must be writable.
 */
int32_t iso532_stream_flush(struct Iso532Stream *handle,
                            struct Iso532StreamFrame *out,
                            size_t out_cap,
                            size_t *out_written);

/**
 * Free a stream handle. A null handle is accepted.
 *
 * # Safety
 * A non-null handle must have been returned by iso532_stream_new and not
 * previously freed.
 */
void iso532_stream_free(struct Iso532Stream *handle);

/**
 * Number of output frames `iso532_loudness_zwtv` will write for a signal of
 * `signal_len` samples, on the ISO 2 ms output grid. Pure; does not validate
 * (validation happens in the main call). Forwards `iso532::zwtv_out_frames`.
 */
size_t iso532_zwtv_out_frames(size_t signal_len);

/**
 * Time-varying (zwtv) loudness. Caller allocates every buffer:
 * out_n[frames], out_n_specific[240*frames] (bark-major, row-major),
 * out_bark[240], out_time[frames]; frames = iso532_zwtv_out_frames(signal_len).
 * Returns 0 on success (see error-code defines). Uses a process-wide thread
 * pool (rayon).
 *
 * # Safety
 * `signal` must be non-null, 8-byte aligned (a valid `double*`), and valid
 * for `signal_len` reads; each out pointer must be valid (and 8-byte
 * aligned) for the writes documented above. `field_type` must be
 * ISO532_FIELD_FREE (0) or ISO532_FIELD_DIFFUSE (1); other values return
 * ISO532_ERR_INVALID_FIELD_TYPE.
 */
int32_t iso532_loudness_zwtv(const double *signal,
                             size_t signal_len,
                             double fs,
                             int32_t field_type,
                             double *out_n,
                             double *out_n_specific,
                             double *out_bark,
                             double *out_time);

/**
 * Stationary (zwst) loudness. Caller allocates: out_n[1],
 * out_n_specific[240], out_bark[240]. Returns 0 on success.
 *
 * # Safety
 * `signal` must be non-null, 8-byte aligned (a valid `double*`), and valid
 * for `signal_len` reads; each out pointer must be valid (and 8-byte
 * aligned) for the writes documented above. `field_type` must be
 * ISO532_FIELD_FREE (0) or ISO532_FIELD_DIFFUSE (1); other values return
 * ISO532_ERR_INVALID_FIELD_TYPE.
 */
int32_t iso532_loudness_zwst(const double *signal,
                             size_t signal_len,
                             double fs,
                             int32_t field_type,
                             double *out_n,
                             double *out_n_specific,
                             double *out_bark);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ISO532_H */
