"""Generate iso532/src/tables_noct.rs: scipy-exact SOS coefficients for the
zwst 28-band 1/3-octave filter bank (ANSI S1.1 Butterworth order 3) and the
Chebyshev-I decimation filters, all fixed because fs is pinned to 48 kHz.
Run: .venv/Scripts/python tools/gen_tables.py
"""
from pathlib import Path

import numpy as np
from scipy.signal import butter, cheby1

FS = 48000
ROOT = Path(__file__).resolve().parent.parent


def center_freqs():
    # mosqito _center_freq(fmin=24, fmax=12600, n=3, G=10, fr=1000):
    # U = 10**(3*b/10) with b=1/3 -> U = 10**0.1
    u = 10 ** 0.1
    kmin = int(np.round(np.log10(24 / 1000) / np.log10(u)))
    kmax = int(np.round(np.log10(12600 / 1000) / np.log10(u)))
    return 1000 * u ** np.arange(kmin, kmax + 1)


def alpha(fc, n=3, N=3):
    b = 1 / n
    f1 = fc / (2 ** (b / 2))
    f2 = fc * (2 ** (b / 2))
    qr = fc / (f2 - f1)
    qd = (np.pi / 2 / N) / (np.sin(np.pi / 2 / N)) * qr
    return (1 + np.sqrt(1 + 4 * qd**2)) / 2 / qd


def decim_q(fc, fs=FS):
    if fc >= fs / 200:
        return 1
    q = 2
    while fc < fs / q / 200:
        q += 1
    return q


def fmt_sos(sos):
    rows = []
    for b0, b1, b2, a0, a1, a2 in sos:
        assert abs(a0 - 1.0) < 1e-15
        # float() strips numpy scalar wrappers; repr(float) round-trips exactly
        # and is valid Rust literal syntax (e.g. 0.001, 1e-05).
        vals = [repr(float(v)) for v in (b0, b1, b2, a1, a2)]
        rows.append(
            "    Sos { b: [%s, %s, %s], a: [%s, %s] }," % tuple(vals)
        )
    return "\n".join(rows)


def main():
    fcs = center_freqs()
    assert len(fcs) == 28, len(fcs)
    al = alpha(fcs)
    lines = [
        "//! GENERATED by tools/gen_tables.py -- do not edit by hand.",
        "//! scipy-exact SOS for the zwst noct_spectrum filter bank at fs=48kHz.",
        "use crate::dsp::sos::Sos;",
        "",
    ]
    qs, all_sos = [], []
    for fc, a in zip(fcs, al):
        q = decim_q(fc)
        fs_eff = FS / q
        w1 = fc / (fs_eff / 2) / a
        w2 = fc / (fs_eff / 2) * a
        sos = butter(3, (w1, w2), "bandpass", output="sos")
        qs.append(q)
        all_sos.append(sos)
    lines.append("#[rustfmt::skip]")
    lines.append(f"pub const NOCT_DECIM_Q: [usize; 28] = {qs!r};".replace("'", ""))
    lines.append("")
    lines.append("#[rustfmt::skip]")
    lines.append("pub const NOCT_SOS: [[Sos; 3]; 28] = [")
    for sos in all_sos:
        lines.append("  [")
        lines.append(fmt_sos(sos))
        lines.append("  ],")
    lines.append("];")
    lines.append("")
    uq = sorted(set(q for q in qs if q > 1))
    lines.append("#[rustfmt::skip]")
    lines.append(f"pub const CHEBY_QS: [usize; {len(uq)}] = {uq!r};")
    lines.append("#[rustfmt::skip]")
    lines.append(f"pub const CHEBY_SOS: [[Sos; 4]; {len(uq)}] = [")
    for q in uq:
        sos = cheby1(8, 0.05, 0.8 / q, output="sos")
        lines.append("  [")
        lines.append(fmt_sos(sos))
        lines.append("  ],")
    lines.append("];")
    out = ROOT / "iso532" / "src" / "tables_noct.rs"
    out.write_text("\n".join(lines) + "\n")
    print("wrote", out, "| qs =", qs)


if __name__ == "__main__":
    main()